# for redhat-actions/buildah-build
FROM ghcr.io/catthehacker/ubuntu:act-latest

RUN apt-get update && \
    apt-get -y --no-install-recommends install buildah podman

COPY registries.conf /etc/containers/registries.conf
COPY --chown=runner:runner \
     config.json \
     /root/.docker/config.json 
